version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./structure:/structure
      - ./objects:/objects
      - ./backups:/backups
    ports:
      - "3309:3306"

    
# COMANDO PARA LEVANTARLO
# docker compose up
